[package]
name = "day7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blondie = "0.4.1"
fxhash = "0.2.1"

[profile.release]
debug = true
